import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const evolventa = localFont({
  src: [
    {
      path: './evolventa/bold.woff',
      weight: 'bold',
      style: 'normal',
    },
    {
      path: './evolventa/boldoblique.woff',
      weight: 'bold',
      style: 'italic',
    },
    {
      path: './evolventa/regular.woff',
      weight: 'normal',
      style: 'normal',
    },
    {
      path: './evolventa/oblique.woff',
      weight: 'normal',
      style: 'italic',
    },
  ],
  variable: "--font-primary",
})

const geist = localFont({
  src: './geist/GeistVariableVF.woff2',
  variable: "--font-second",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${evolventa.variable} ${geist.variable}`}>
      {children}
    </html>
  );
}
